#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" >> /etc/default/haproxy

printf %s "
backend web-backend
    balance roundrobin
    server 375-web-01 104.196.168.90:80 check
    server 375-web-02 35.196.46.172:80  check
" >> /etc/haproxy/haproxy.cfg

service haproxy restart
