#!/usr/bin/env bash
# Generates a compressed archive of a MySQL dump.
mysqldump -uroot -p"$1" --all-databases > backup.sql 2>&1 | grep -v "Warning: Using a password"
tar -cvzf "$(date +%d-%m-%y)".gz backup.sql
