#!/usr/bin/env bash
# Displays "Holberton School" 10 times using a while loop.
#   On the 9th iteration, displays "Hi" before "Holberton School".

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Holberton School"
  (( count++ ))
done
