#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page.
# The redirection is configured as a "301 Moved Permanently"

apt-get update
apt-get install -y nginx
service nginx start

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Holberton School" > index.html
printf
"server {
    listen 80;
    root /etc/nginx/html;
    index index.html;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }
}" > /etc/nginx/sites-available/default

nginx -s reload
